#name: Build and Deploy
#
#on:
#  push:
#    branches:
#      - develop
#
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '20'
#
#      - name: Install dependencies
#        run: npm install
#
#      - name: Build project
#        run: npm run build:stage
#
#      - name: Create artifact
#        run: npm run artifact
#
#      - name: Deploy artifact to remote server
#        uses: appleboy/scp-action@master
#        with:
#          host: 000.000.000.000
#          username: ms
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          source: "artifact.zip"
#          target: "~/www"
#
#      - name: Prepare and Unpack artifact
#        uses: appleboy/ssh-action@master
#        with:
#          host: 000.000.000.000
#          username: ms
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: |
#            rm -rf ~/www/html
#            unzip ~/www/artifact.zip -d ~/www/html